package utility;

public enum MessageType {	
	AUTH_MESSAGE,
	PERSONAL_MESSAGE,
	EXIT_MESSAGE,
	BROADCAST_MESSAGE,
	ADD_USER_MESSAGE,
	DEACTIVATE_USER_MESSAGE,
	PLAIN_MESSAGE,
	CHANGE_NICK_MESSAGE
}
